spring:
  application:
    name: jeonggiju
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


security:
  jwt:
    issuer: life-project
    access-secret-key: ${JWT_ACCESS_KEY}
    refresh-secret-key: ${JWT_REFRESH_KEY}
    access-token-validation-seconds: 900
    refresh-token-validation-seconds: 86400